<<<<<<< HEAD
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
=======
import { Box, Button, Card, Center, Group, Modal, Stack, Title, Text, SimpleGrid, Space, Footer, Grid } from "@mantine/core";
import { useViewportSize } from "@mantine/hooks";
import Link from "next/link";
import{ useRouter } from "next/router";
import { useEffect, useState } from "react";
import useApi from "../useApi";

export default function Home() {

  let router = useRouter();
  let api = useApi();
  const {width, height} = useViewportSize();
  const [lessons, setLessons] = useState([]);
  const [opened, setOpened] = useState(false);
  //State used to determine what lesson to delete
  const [delId, setDelId] = useState(0);

  //Get info from backend and save into state
  useEffect(() => {
    api.getAllLessons()
       .then(data => {
        console.log("Lessons:");
          console.log(data)
          setLessons(data)
       })
  }, []);

  let deleteLesson = (lessonId) => {
    api.deleteLesson(lessonId)
    .then(data => {
      console.log(data);
      // router.reload(window.location.pathname);
      setOpened(false);
    })
    .catch(err => {
      console.error(err);
      alert("Error deleting lesson")
    })
  }

  return (
    <>
    <Center> 
        <Stack mt={20} sx={{width:width, height:(height-20)}}>
          <Center>
            <Link
              passHref
              href={"/createLesson/"}
            >
              <Button>Create Lesson</Button>
            </Link>
          </Center>
          <SimpleGrid cols={3} px={60}>
            {lessons.map((item, key) => {
              return (
                <Card
                  key={key}
                  radius={"md"}
                >
                  <Card.Section>
                    <Box
                      sx={(theme) => ({ 
                        padding: "10px",
                        background: "rgb(131,58,180)",
                        background: "linear-gradient(0deg, rgba(131,58,180,1) 0%, rgba(253,29,29,1) 50%, rgba(252,176,69,1) 100%)",
                        height: 150
                      })}
                    >
                    </Box>
                  </Card.Section>
                  <Center>
                    <Title order={3}>{item.title}</Title>
                  </Center>
                  <Space h={"sm"}/>
                  <Group position="center">
                    {/* Opens dialogue for deleting a lesson */}
                    <Button color={"red"}
                      onClick={() => {
                        setDelId(item.id);
                        setOpened(true)
                      }}
                      >
                      Delete
                    </Button>
                    <Link
                      passHref
                      href={`/editLesson/${item.id}`}
                    >
                      <Button color={"blue"}>
                        Edit
                      </Button>
                    </Link>
                    <Link
                      passHref
                      href={`/lesson/${item.id}`}
                    >
                      <Button color={"green"}>
                        View
                      </Button>
                    </Link>
                  </Group>
                </Card>
              )
            })}
          </SimpleGrid>
      </Stack>
    </Center>


    <Modal
      size={550}
      opened={opened}
      onClose={() => setOpened(false)}
    >
      <Stack>
        <Title align="center">Are you sure you want to delete this lesson?</Title>
        <Text align="center">This will delete all steps associated with this lesson.</Text>
        <Button color={"red"} onClick={() => {deleteLesson(delId)}}>
          Delete Component
        </Button>
      </Stack>
    </Modal>
    </>
  )
}
>>>>>>> b7f7eab77916d404e57b3ceb609ff6e9af3a733e
